<?php
DEFINE('RSSATOMAV_ERR_GET_IMG_SIZE','Ошибка: не удалось получить размер изображения...');
DEFINE('RSSATOMAV_OPTIONS_FAIL','Не удалось сохранить настройки');
DEFINE('RSSATOMAV_OPTIONS_SAVED','Настройки сохранены');
DEFINE('RSSATOMAV_HOMEPAGE','Страница плагина');
DEFINE('RSSATOMAV_FEEDBACK','Отзывы');
DEFINE('RSSATOMAV_FEED_ICON_ATOM','Иконка (favicon, только для ATOM)');
DEFINE('RSSATOMAV_URL_HINT','Полный адрес, скорее всего, начинается с');
DEFINE('RSSATOMAV_USE_ICO','Используйте файл иконки (*.ico)');
DEFINE('RSSATOMAV_RSS_SPEC','<strong style="color:#000000;">У стандарта RSS есть ограничения по высоте и ширине</strong><br>Максимальная ширина <em>144</em>, по умолчанию - <em>88</em>.<br>Максимальная высота <em>400</em>, по умолчанию - <em>31</em>.');
DEFINE('RSSATOMAV_FEED_LOGO','Аватар (большая картинка, для ATOM и RSS)');
DEFINE('RSSATOMAV_USE_IMAGE','используйте обычное изображение (jpg, png, gif)');
DEFINE('RSSATOMAV_IMAGE_DIM','Размеры изображения');
DEFINE('RSSATOMAV_WIDTH','Ширина');
DEFINE('RSSATOMAV_HEIGHT','Высота');
DEFINE('RSSATOMAV_TRY_AUTODETECT','Автоматически определить размеры картинки');
?>