<?php
DEFINE('RSSATOMAV_ERR_GET_IMG_SIZE','Error: Failed to get logo image size...');
DEFINE('RSSATOMAV_OPTIONS_FAIL','Failed to save options');
DEFINE('RSSATOMAV_OPTIONS_SAVED','Options Saved');
DEFINE('RSSATOMAV_HOMEPAGE','Plugin Homepage');
DEFINE('RSSATOMAV_FEEDBACK','Feedback');
DEFINE('RSSATOMAV_FEED_ICON_ATOM','Feed Icon (favicon, only for ATOM)');
DEFINE('RSSATOMAV_URL_HINT','full url, probably beginning from');
DEFINE('RSSATOMAV_USE_ICO','Use an icon file (*.ico)');
DEFINE('RSSATOMAV_RSS_SPEC','<strong style="color:#000000;">RSS has specifications about logo height and width</strong><br>Maximum value for width is <em>144</em>, default value is <em>88</em>.<br>Maximum value for height is <em>400</em>, default value is <em>31</em>.');
DEFINE('RSSATOMAV_FEED_LOGO','Feed Logo (big image, avatar, for both ATOM and RSS feeds)');
DEFINE('RSSATOMAV_USE_IMAGE','Use an image file (jpg, png, gif)');
DEFINE('RSSATOMAV_IMAGE_DIM','Image Dimensions');
DEFINE('RSSATOMAV_WIDTH','Width');
DEFINE('RSSATOMAV_HEIGHT','Height');
DEFINE('RSSATOMAV_TRY_AUTODETECT','Try to auto detect dimensions');
?>